name: csh
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  # UI
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0
  # State & Logic
  provider: ^6.1.0
  # Database & Security
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  encrypt: ^5.0.3
  # Hardware Sensors
  device_info_plus: ^9.0.0
  disk_space_2: ^1.0.12
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  url_launcher: ^6.2.0
  percent_indicator: ^4.2.5
  http: ^1.2.0
  dart_rss: ^3.0.3
  file_picker: ^8.0.0
  path_provider: ^2.1.0
  path: ^1.9.1
  xml: ^6.5.0
  pattern_lock: ^2.0.0
  
  safe_device: ^1.3.8


  # --- HARDWARE & SENSORS ---
  connectivity_plus: ^5.0.0
  sensors_plus: ^5.0.0
  vibration: ^3.1.6
  local_auth: ^2.2.0
  camera: ^0.11.0
  battery_plus: ^5.0.0
  audioplayers: ^5.2.1
  record: ^5.1.2 # Bumped from 5.1.0
  screen_brightness: ^0.2.2
  flutter_volume_controller: ^1.3.3
  permission_handler: ^11.0.0
  proximity_sensor: ^1.2.0
  light_sensor: ^3.0.2
  audio_session: ^0.1.21
  shared_preferences: ^2.2.0
  flutter_overlay_window: ^0.5.0
  home_widget: ^0.9.0
  fl_chart: ^1.2.0
  android_intent_plus: ^5.0.0
  app_settings: ^6.0.0
  network_info_plus: ^5.0.0
  system_info2: ^4.0.0
  installed_apps: ^1.1.0
  storage_space: ^1.2.0
  package_info_plus: ^8.0.0
  flutter_native_timezone_latest: ^1.0.0
  open_filex: ^4.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.0
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/test_beep.mp3
    - assets/app_icon.png

dependency_overrides:
  record_web: ^1.1.0 # Added to fix the web compilation error
  record_linux: ^1.2.0
  vector_math: ^2.3.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 23
